version: '3.7'

services:
  share-movie-backend:
    container_name: share-movie-backend
    image: share-movie-backend
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - ${PUBLIC_API_PORT}:${PUBLIC_API_PORT}
    restart: always
    depends_on:
      - share-movie-db

  share-movie-db:
    container_name: share-movie-db
    image: "mariadb:latest"
    env_file:
      - .env
    ports:
      - ${MARIADB_PORT}:${MARIADB_PORT}
    restart: unless-stopped
    volumes:
      - ./.db_prod/conf.d:/etc/mysql/conf.d
      - ./.db_prod/logs:/logs
      - ./.db_prod:/var/lib/mysql

volumes:
  .db_prod:
