version: '3.7'

services:
  share-movie-backend:
    container_name: share-movie-backend
    image: gcr.io/sound-catalyst-382708/share-movie-backend:latest
    env_file:
      - .env
    ports:
      - ${PUBLIC_API_PORT}:${PUBLIC_API_PORT}
    restart: always
    depends_on:
      - share-movie-db

  share-movie-db:
    container_name: share-movie-db
    image: "mysql:latest"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: movie_password
      MYSQL_DATABASE: share_movies
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.db_data:/var/lib/mysql
volumes:
  .db_data:
