version: '3.7'

services:
  share-movie-api:
    container_name: public-api
    image: shared-movie
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    restart: always
    depends_on:
      - share-movie-db

  share-movie-db:
    container_name: share-movie-db
    image: "mysql:latest"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: movie_password
      MYSQL_DATABASE: share_movies
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.db_data:/var/lib/mysql
volumes:
  .db_data:


