name: Deploy to Production

on:
  pull_request:
    types: [closed]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Building and pushing the image
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta # <- use this on your workflow
        with:
          gcloud_service_key: '${{ secrets.JSON_GCLOUD_SERVICE_ACCOUNT_JSON }}'
          registry: gcr.io
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          image_name: ${{ env.IMAGE_NAME }}
          image_tag: latest, ${{ github.sha }}
          dockerfile: ./Dockerfile
          context: ./
          target: build

    env:
      IMAGE_NAME: share-movie-backend

  deploy-api:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Authenticate GCP'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.JSON_GCLOUD_SERVICE_ACCOUNT_JSON }}'

      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: '22'
          username: ${{ secrets.SSH_USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          script: sh ./share-movie-backend.sh
