on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16']
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run testing by Jest
        run: npm run test

  build-and-push:
    needs: test-api
    if: ${{ success() }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo ${{ env.CR_PAT }} | docker login ghcr.io -u ${{env.GITHUB_USER}} --password-stdin

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{env.GITHUB_USER}}/${{env.IMAGE_NAME}}:latest,ghcr.io/${{env.GITHUB_USER}}/${{env.IMAGE_NAME}}:${{ github.sha }}
    env:
      IMAGE_NAME: share-movie-backend
      GITHUB_USER: ngtrdai197
      CR_PAT: ${{ secrets.CR_PAT }}
